- auth0/v2/authentication/database.py
- auth0/v2/authentication/delegated.py
- auth0/v2/authentication/passwordless.py
- auth0/v2/authentication/social.py
- auth0/v2/test/authentication/test_database.py
- auth0/v2/test/authentication/test_delegated.py
- auth0/v2/test/authentication/test_passwordless.py
- auth0/v2/test/authentication/test_social.py
Each of the authentication types currently hardcodes scope to use
'openid' only. As this is something that a user might want to change,
make this a parameter for each of the login/get_token methods.
Also, adjust tests accordingly.
> Do not hardcode scope for just openid

- examples/flask-api/server.py
> Change flask.ext.cors to flask_cors to prevent deprecation warning

- auth0/v3/management/rules.py
- auth0/v3/test/management/test_rules.py
I found a bug in the Rules.all method that causes limited behavior in the Python API compared to what is allowed by the REST API.  The REST API specified the boolean parameter `enabled`, which if `true` will result in only rules that are enabled being returned by the API.  If `false`, only rules that are disabled will be returned by the API.  If this parameter is not provided, then all rules will be returned regardless of whether they are enabled or disabled.
The Python API only supports providing `True` or `False` for the `enabled` parameter in the Rules.all function, which results in the enabled parameter always being included in the request to the REST API.  This means that one cannot request all rules regardless of enabled or disabled in a single request.
I've updated the Rules.all …
> Updated Rules.all to exclude enabled parameter if enabled=None

- auth0/v3/authentication/get_token.py
- auth0/v3/test/authentication/test_get_token.py
The Auth0 Authentication API supports the `refresh_token` grant type, but the auth0-python package does not support it in the Python SDK.  I've added a new method to GetToken.py called `refresh_token`, which accepts `client_id`, `client_secret`, `refresh_token`, and `grant_type='refresh_token'` as arguments.  This calls the `/oauth/token` endpoint of the Auth0 Authentication API with the `refresh_token` grant type and returns an `access_token` and `id_token`.  I also added test for this new method.
> Added refresh_token to GetToken

- auth0/v3/management/jobs.py
- auth0/v3/test/management/test_jobs.py
The Auth0 Management API supports an `upsert` boolean parameter on the `jobs/users-imports` endpoint, but this parameter is not currently supported in the auth0-python package.  I've added support for this parameter, making it `False` by default so existing users should not be impacted.  I also updated unit tests for jobs to honor this change.
@Annyv2 could you please review this PR and let me know if I need to change anything?
> Added upsert parameter to import users job

- auth0/v3/authentication/base.py
- auth0/v3/test/authentication/test_base.py
Hello. We've seen this problem in our running system when calling `GetToken.client_credentials()`. We currently have to parse the response text to see if it looks like an error message rather than a token.
> Correctly throw an exception when handing a text response

- auth0/v3/management/auth0.py
This prevents the user from having to instantiate the class on their own.
This will fix #89, I'm mainly making this to start the conversation (and to see if it passes tests)
> Instantiate UserBlocks for consistency

- auth0/v3/authentication/base.py
- auth0/v3/management/rest.py
- auth0/v3/test/authentication/test_base.py
- auth0/v3/test/management/test_rest.py
I copied the logic from authentication/base.py for _process_response into management/rest.py.  This way any 400 or greater status codes will result in an Auth0Error.
The current functionality, which is based on 'error_code' being present in the response is not good enough because not all Auth0 API error response include 'error_code' and thus bad response get through when the expectation is a valid object.  For example, if I call auth0.users.create() and get a 429 response, the API response does not have an error_code and my code expects to receive a valid user profile but instead receives a `{"error": "Too Many Requests", "status_code": 429}`.
This change will make consuming the auth0-python sdk more consistent as all error responses will result in an Auth0Error instead of some resulting …
> Raise Auth0Error for bad status code

- .gitignore
- auth0/v3/management/clients.py
- auth0/v3/management/connections.py
- auth0/v3/test/management/test_clients.py
- auth0/v3/test/management/test_connections.py
This PR adds pagination support on MGMT API entities that were missing.
- While pagination is going to be enforced on new tenants, existing tenants can still call the endpoint without a `page` value and in turn, retrieve the full list of items. However for this specific SDK, the entities that already had pagination implemented had a default `page` value of `0`, meaning if a specific page is not asked, the first one is always returned. On the present PR the new entities supporting pagination don't have the same behavior. Instead, they skip sending the `page` parameter if no value is specified. **Should we maintain the same pagination behavior as other entities or avoid a possible breaking change?**
I re-used the existing tests and added a few similar. I noticed the tests were actually …
> Add pagination to Clients and Connections

- auth0/v3/authentication/passwordless.py
- auth0/v3/management/clients.py
- auth0/v3/management/connections.py
- auth0/v3/management/device_credentials.py
- auth0/v3/management/emails.py
- auth0/v3/management/rest.py
- auth0/v3/management/rules.py
- auth0/v3/management/tenants.py
- auth0/v3/management/users.py
- auth0/v3/test/management/test_rest.py
This PR fixes a possible issue with default mutable arguments. More info [here](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html#anti-pattern).
The `request` library has as default `None` for all optional arguments so this is not a breaking change. [(source)](http://docs.python-requests.org/en/master/_modules/requests/api/?highlight=get)
Related PR: https://github.com/auth0/auth0-python/pull/93
> Replace default mutable arguments with None

- auth0/v3/management/client_grants.py
- auth0/v3/management/clients.py
- auth0/v3/management/connections.py
- auth0/v3/management/device_credentials.py
- auth0/v3/management/emails.py
- auth0/v3/management/logs.py
- auth0/v3/management/resource_servers.py
- auth0/v3/management/rules.py
- auth0/v3/management/tenants.py
- auth0/v3/management/users.py
- auth0/v3/test/management/test_client_grants.py
- auth0/v3/test/management/test_resource_servers.py
- auth0/v3/test/management/test_rules.py
This PR adds pagination support on MGMT API entities that were missing. 
I kept this free from breaking changes by providing an `include_totals=False` value (since if that's true, the response is an Object rather than an Array).
✅ Unit tests asserting the params with which the function was called. Similar to the other pagination PR.
> Add pagination to Client Grants, Resource Servers and Rules

- setup.py
Right now, https://pypi.org/project/auth0-python/ looks like:
Instead of "The author of this package has not provided a project description", we can put the contents of the README there. This is what Python packages commonly do.
> Use README.rst as long_description on PyPI

- auth0/v3/management/connections.py
- auth0/v3/test/management/test_connections.py
> Implemented delete_user_by_email and test for connections

- auth0/v3/management/jobs.py
- auth0/v3/test/management/test_jobs.py
Adds the `users-exports` endpoint to the SDK for user database export job creation.
> Adds user export job creation.

- dockerfile
The use of COPY is preferred over ADD when additional functionalities of ADD are not being used (like spraying the contents of a tar in a folder).
> Used COPY instead of ADD.

- auth0/v3/management/users_by_email.py
- auth0/v3/test/management/test_users_by_email.py
Per the documentation here:
https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email
> If Auth0 is the identify provider (idP), the email address associated with a user is saved in lower case, regardless of how you initially provided it. For example, if you register a user as JohnSmith@example.com, Auth0 saves the user's email as johnsmith@example.com.
> 
> **In cases where Auth0 is not the idP, the `email` is stored based on the rules of idP, so make sure the search is made using the correct capitalization.**
> Stop lower-casing email on user search

- auth0/v3/management/client_grants.py
- auth0/v3/test/management/test_client_grants.py
> Add `client_id` param to ClientGrants.all

- README.rst
I accidentally force pushed without making the new commit and Github closed the pull request [https://github.com/auth0/auth0-python/pull/157]. New pushes aren't updating the PR for me, so creating this new one. 
Changed the text from `end-of-life` to `EOL` because `-` was messing up the markup rendering. 
See : https://github.com/auth0/auth0-python/pull/157#pullrequestreview-171707418
> Fix EOL hyperlink in README.

- auth0/v3/authentication/authorize_client.py
- auth0/v3/authentication/base.py
- auth0/v3/authentication/database.py
- auth0/v3/authentication/delegated.py
- auth0/v3/authentication/enterprise.py
- auth0/v3/authentication/get_token.py
- auth0/v3/authentication/logout.py
- auth0/v3/authentication/passwordless.py
- auth0/v3/authentication/social.py
- auth0/v3/authentication/users.py
- auth0/v3/test/authentication/test_base.py
Added a `telemetry` kwarg to the `AuthenticationBase` constructor and (mostly) matched the telemetry behavior from the management `RestClient` class.
fixes #136
> Add telemetry headers to AuthenticationBase

- auth0/v3/authentication/revoke_token.py
- auth0/v3/test/authentication/test_revoke_token.py
Closes https://github.com/auth0/auth0-python/issues/115
> Add Revoke Refresh Token endpoint

- auth0/v3/management/users.py
- auth0/v3/test/management/test_users.py
Search engine v2 is no longer available for new tenants. This caused frustration for those using this library without passing a specific value for the `search_engine` feature when querying for users.
This PR removes the default value of `v1` (even older, and already disabled a long time ago). This way, those not specifying a value will default to the backend's latest version. Currently v3.
Those already passing a fixed value will see no effect.
> User search v2 has been deprecated as of June 6th 2018. Tenants created after this date will not have the option of using it. We recommend that you use User Search v3 instead.
https://auth0.com/docs/users/search/v2
https://auth0.com/docs/users/search/v3
> Remove default value for search_engine

- auth0/v3/management/clients.py
- auth0/v3/test/management/test_clients.py
The rotate client secret endpoint expects a POST request, not a GET. This PR fixes it.
Will close https://github.com/auth0/auth0-python/issues/189
> Fix HTTP method used for rotating Client secret

- auth0/v3/management/rules_configs.py
- auth0/v3/test/management/test_rules_configs.py
Changes `rules_config.unset` to pass the `key` param as a path param instead of a query param. This fixes the 404 error previously being returned.
Closes #194 
Fixed existing unittest.
> rules_config.unset fix

- requirements.txt
This PR bumps the requests version required by the SDK. Now instead of requiring a fix version, it's only required a minimum.
I'd release this on a new minor (not patch).
Did not need to change the tests, all pass fine.
> Update requests dependency to latest version

- auth0/v3/authentication/base.py
- auth0/v3/authentication/database.py
- auth0/v3/authentication/delegated.py
- auth0/v3/authentication/get_token.py
- auth0/v3/authentication/logout.py
- auth0/v3/authentication/passwordless.py
- auth0/v3/authentication/social.py
- auth0/v3/authentication/users.py
- auth0/v3/management/rest.py
- auth0/v3/test/authentication/test_base.py
- auth0/v3/test/authentication/test_database.py
- auth0/v3/test/authentication/test_delegated.py
- auth0/v3/test/authentication/test_get_token.py
- auth0/v3/test/authentication/test_logout.py
- auth0/v3/test/authentication/test_passwordless.py
- auth0/v3/test/authentication/test_social.py
- auth0/v3/test/authentication/test_users.py
- auth0/v3/test/management/test_rest.py
There was an error affecting only the `authentication` API client and methods exposed on this SDK. When the call was not specifying custom headers (headers=None) a call to dictionary#update would fail. 
This PR fixes that issue, as well as a response converting issue.
I manually run this directly calling the requests library. Also run the AuthenticationBase#post/get calls.
- Added missing tests for the "default" scenario on those 2 methods.
- Added missing tests for the `management#put` method.
> Fix request creation when headers are the default

- auth0/v3/authentication/passwordless.py
- auth0/v3/test/authentication/test_passwordless.py
Tenants created after January 2, 2020 are required to set the client_secret when starting the passwordless flow.
API docs https://auth0.com/docs/api/authentication?#get-code-or-link
Migration guide: https://auth0.com/docs/migrations/guides/passwordless-start
Added tests for the optional parameter
> Accept client_secret as passwordless/start param

- README.rst
- auth0/v3/authentication/token_verifier.py
- auth0/v3/exceptions.py
- auth0/v3/test/authentication/test_token_verifier.py
- requirements.txt
This update improves the SDK support for OpenID Connect. In particular, it modifies the sign in verification phase by adding on top of the backchannel checks the option to perform id_token validation.
> Improved OIDC compliance

- auth0/v3/management/users.py
This method was added 5 years ago. It seems it is no longer available nor documented on the API2 docs. This PR prints a warning to whoever is still calling it. 
The use of the method would result on a 404 response from the server.
https://auth0.com/docs/api/management/v2#!/Users
> Add deprecation note for DELETE /users (all users)

- README.rst
- auth0/v3/authentication/base.py
- auth0/v3/exceptions.py
- auth0/v3/management/rest.py
- auth0/v3/test/authentication/test_base.py
- auth0/v3/test/management/test_rest.py
When too many requests have been made against the server, the next request will fail with a `429`. In the response headers there will be extra information, such as the time at which this limit is reset.
With this PR: 
* `429` errors are raised as `RateLimitError` instead of `Auth0Error`. 
* They will expose a property `reset_at` with the value of the `X-RateLimit-Reset` header. This value represents the Unix timestamp at which the limit will be reset.
* When this header is not set, a value of -1 will be set as default.
More info https://auth0.com/docs/policies/rate-limits
> Expose the time at which the Rate Limit will reset

- auth0/v3/management/jobs.py
- auth0/v3/test/management/test_jobs.py
Add missing parameter when creating a users import job.
Resolves https://github.com/auth0/auth0-python/issues/210
> Add send_completion_email to users import job

- auth0/v3/authentication/token_verifier.py
- auth0/v3/test/authentication/test_token_verifier.py
According to the spec, checking this value should be optional. Presence check however is not. That remains.
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation
> The iat Claim **can** be used to reject tokens that were issued too far away from the current time, limiting the amount of time that nonces need to be stored to prevent attacks. The acceptable range is Client specific.
> Remove iat claim value check

- auth0/v3/management/jobs.py
- auth0/v3/test/management/test_jobs.py
The endpoint was missing the `external_id` property.
Resolves `SDK-1625`
> Add missing external_id property to the import users job

- auth0/v3/authentication/token_verifier.py
This addresses the incorrect docstrings described in #225.
This should fix #225.
n/a, this only changes docstrings.
> fix docstrings for A/SymmetricSignatureVerifiers

- auth0/v3/authentication/database.py
- auth0/v3/test/authentication/test_database.py
There are extra properties that could be specified on the sign up call, documented in swagger [here](https://auth0.com/docs/api/authentication#signup). This PR adds them, defaulting to `None` when not specified.
Closes https://github.com/auth0/auth0-python/issues/229
> Add missing user profile properties to the signup endpoint

- auth0/v3/authentication/database.py
- auth0/v3/authentication/delegated.py
- auth0/v3/authentication/revoke_token.py
- auth0/v3/management/blacklists.py
- auth0/v3/test/authentication/test_database.py
- auth0/v3/test/authentication/test_revoke_token.py
- auth0/v3/test/management/test_blacklists.py
The python request library when it creates the query parameters, it will remove any parameter on the passed dict that has a value of `None`. In our library, these are only used for GET requests.
For the case of POST or PATCH requests, the dict that conforms the body will not suffer the same filtering.
In some cases it makes sense to send an explicit null value, like when removing a property from the user's `user_metadata` property, the check should be performed on each POST/PATCH function instead of in the base client class.
The PR also includes some linting fixes, related to doc blocks and formatting. 
Fixes https://github.com/auth0/auth0-python/issues/228
Docs on the params filtering https://requests.readthedocs.io/en/master/user/quickstart/#passing-parameters-in-urls. Note it doesn't …
> Skip sending optional parameters on POST request when unspecified

- auth0/v3/management/auth0.py
- auth0/v3/management/hooks.py
- auth0/v3/test/management/test_auth0.py
- auth0/v3/test/management/test_hooks.py
Adds the Hooks management API that was missing in auth0-python, along with unit tests.
It also includes Hooks Secrets management.
API docs: https://auth0.com/docs/api/management/v2#!/Hooks/get_hooks
Closes https://github.com/auth0/auth0-python/issues/224
> Add Hooks management API

- README.rst
- auth0/v3/management/auth0.py
- auth0/v3/management/log_streams.py
- auth0/v3/test/management/test_auth0.py
- auth0/v3/test/management/test_log_streams.py
Adds support for the Log Streams API.
https://auth0.com/docs/api/management/v2/#!/Log_Streams/get_log_streams
I manually tested the endpoints, using the following code (Tweak if necessary)
```python
def testList(self):
api = LogStreams('lbalmaceda.auth0.com', self.token)
res = api.list()
print("\n", res)
def testGetId(self):
api = LogStreams('lbalmaceda.auth0.com', self.token)
res = api.get("lst_0000000000001834")
print("\n", res)
def testDeleteId(self):
api = LogStreams('lbalmaceda.auth0.com', self.token)
res = api.delete("lst_0000000000001835")
print("\n", res)
def testPatchId(self):
api = LogStreams('lbalmaceda.auth0.com', self.token)
res = api.update("lst_0000000000001835", {"name": "nombrecito"})
print("\n", res)
def testCreate(self):
api = LogStreams('lbalmaceda.auth0.com', …
```
> Add support for Log Streams API

- auth0/v3/management/__init__.py
Very simple PR, more of a client developer quality-of-life change than anything, feel free to disregard if not important or wanted.
Currently, importing `Hooks` from the `management` module like so is not possible:
```python
from auth0.v3.management import Hooks
```
This is because in management's [`__init__.py`](https://github.com/auth0/auth0-python/pull/235/files#diff-48ef27daf8c04b9b512106f084418ad8), `Hooks` is not imported. It is still possible to import `Hooks` with the following code:
```python
from auth0.v3.management.hooks import Hooks
```
But when so much else is available at the `management` module level its kind of a pain.
This is a minute change without any implications on functionality, as mentioned above just a quality of life change. Automated testing seems inappropriate, …
> Fix imports on the management/__init__.py file

- auth0/v3/management/users.py
- auth0/v3/test/management/test_users.py
- Adds a missing endpoint to invalidate all remembered browsers (mfa) for a user
https://auth0.com/docs/api/management/v2#!/Users/post_invalidate_remember_browser
> Adds a new user method invalidate_remembered_browsers

- README.rst
- auth0/v3/authentication/authorize_client.py
- auth0/v3/authentication/token_verifier.py
- auth0/v3/test/authentication/test_authorize_client.py
- auth0/v3/test/authentication/test_token_verifier.py
This PR adds support for the (beta) Organizations and User Invitations features. Changes included:
- Supports specifying the organization and invitation query parameters when using the `AuthorizeClient`.
- Supports verification of the `org_id` claim in `TokenVerifier`
- Adds documentation for using the Organizations and User Invitations features
> Add support for organizations feature

- README.rst
Add guidance on how to verify the Access Token contents, particularly the "org_id" claim. This is recommended in the case of using this SDK in an API/Backend application type.
> Add access token validation guidance for organizations

- README.rst
- auth0/v3/management/auth0.py
- auth0/v3/management/organizations.py
- auth0/v3/management/users.py
- auth0/v3/test/management/test_auth0.py
- auth0/v3/test/management/test_organizations.py
- auth0/v3/test/management/test_users.py
Adds endpoints to manage Organizations through the MGMT APIs.
- POST Organization
- PATCH Organization
- GET Organizations
- GET Organization
- GET Organization (by name)
- DELETE Organization
- POST Organization Connection
- PATCH Organization Connection
- GET Organization Connections
- GET Organization Connection
- DELETE Organization Connection
- POST Organization Members
- GET Organization Members
- DELETE Organization Members
- POST Organization Member Roles
- GET Organization Member Roles
- DELETE Organization Member Roles
- POST Organization Invitations
- GET Organization Invitations
- GET Organization Invitation
- DELETE Organization Invitations
- GET User Organizations
See `SDK-2439`
Unit tests were provided. These endpoints have not been manually tested yet.
> Add support for Organization MGMT API endpoints [SDK-2439]

- auth0/v3/management/organizations.py
- auth0/v3/test/management/test_organizations.py
- Endpoints added, deleted, deprecated, or changed
There is an error in `organizations.get_organization_by_name`. The path from the docs should be `/api/v2/organizations/name/{name}`. The current implementation, however, just uses the default `/api/v2/organizations` and sends the `name` parameter (which is invalid and throws an error).
- Pull request https://github.com/auth0/auth0-python/issues/268
- [API documentation](https://auth0.com/docs/api/management/v2#!/Organizations/get_name_by_name)
I'm sorry but I can't see how to run the existing test. Please point me to the instructions and I'll update the PR.
> Repair Organisation get by name URL.

- auth0/v3/management/jobs.py
- auth0/v3/test/management/test_jobs.py
It appears like the endpoint to get a job's result has been removed from the Management API2 definition. While the endpoint is no longer accessible, the function call can be re-routed to the existing get-job-by-id function, which would yield the job status along with their results
See #274
> Re-Route Job Results endpoint

- auth0/v3/management/organizations.py
- auth0/v3/management/roles.py
- auth0/v3/test/management/test_organizations.py
- auth0/v3/test/management/test_roles.py
This PR updates the following methods to support checkpoint pagination API2 parameters:
- `Roles::list_users()`
- `Organizations::all_organizations()`
- `Organizations::all_organization_members()`
- Please see the internal Jira tickets SDK-2666 and related epic SDK-2653 for details on this initiative.
> [SDK 2665] Update endpoint methods to support 'from' and 'take' checkpoint pagination parameters, where appropriate

- auth0/v3/authentication/get_token.py
- auth0/v3/authentication/passwordless.py
- auth0/v3/test/authentication/test_get_token.py
- auth0/v3/test/authentication/test_passwordless.py
The `get_token` file was not including the ability to complete the passwordless flow using the /oauth/token endpoint. This PR adds the function that exposes the right grant to use passwordless.
https://auth0.com/docs/api/authentication#authenticate-user
See #252
> Add Passwordless Login function

- auth0/v3/authentication/passwordless.py
This endpoint should no longer available. There's an /oauth/token variant available documented in the swagger docs.
https://auth0.com/docs/api/authentication#authenticate-user
See #279
> Deprecate /oauth/ro for passwordless

- auth0/v3/authentication/token_verifier.py
These changes don't change code, this only corrects the placement of the docstrings for each method and classes on `authentication.token_verifier`
fixes #282 
Run the `make html` for regenarating the docs then navigate to the `authentication.token_verifier` part, now you'll see the corresponding documentation:
> Moves docs for each method into the method itself

- .circleci/config.yml
- docs/Makefile
- docs/source/conf.py
- docs/source/v3.management.rst
Adds a step to build the docs in the CI, failing if something if the syntax is wrong. This will help enforce good docs, now that we publish them to Readthedocs.
List of options: https://www.sphinx-doc.org/en/master/man/sphinx-build.html
- `-W` converts warnings to errors
- `--keep-going` will not stop in the first error, useful to get the complete list of errors.
- `-n` will verify broken links and references
- `-a` runs the docs generation task even when the source code hasn't changed
> Make the CI fail when the docs syntax is invalid

- README.rst
- auth0/v3/management/auth0.py
- auth0/v3/management/prompts.py
- auth0/v3/test/management/test_auth0.py
- auth0/v3/test/management/test_prompts.py
- docs/source/v3.management.rst
Added support for prompts API:
- https://auth0.com/docs/api/management/v2/#!/Prompts/get_prompts
- https://auth0.com/docs/api/management/v2/#!/Prompts/patch_prompts
- https://auth0.com/docs/api/management/v2/#!/Prompts/get_custom_text_by_language
- https://auth0.com/docs/api/management/v2/#!/Prompts/put_custom_text_by_language
Classes added:
- `auth0.v3.management.prompts.Prompts`
Classes modified:
- `auth0.v3.management.auth0.Auth0`
No references
> Added support for prompts API

- README.rst
- auth0/v3/management/__init__.py
- auth0/v3/management/attack_protection.py
- auth0/v3/management/auth0.py
- auth0/v3/test/management/test_atack_protection.py
- auth0/v3/test/management/test_auth0.py
Add the new attack protection endpoints to the management client:
```
GET /api/v2/attack-protection/suspicious-ip-throttling
PATCH /api/v2/attack-protection/suspicious-ip-throttling
GET /api/v2/attack-protection/breached-password-detection
PATCH /api/v2/attack-protection/breached-password-detection
GET /api/v2/attack-protection/brute-force-protection
PATCH /api/v2/attack-protection/brute-force-protection
```
> [SDK-3119] Add attack protection endpoints

- auth0/v3/management/branding.py
- auth0/v3/test/management/test_branding.py
This PR adds `/api/v2/branding` endpoints support for the Management API. It expands our tests to cover the additional class and methods added for support.
> [SDK-3179] Add /api/v2/branding endpoints support

- .circleci/config.yml
Using the last dev version before we release the orb as we have a chance to test it end-to-end.
> Bump ship/orb version

- auth0/v3/management/organizations.py
- auth0/v3/test/management/test_organizations.py
No pagination properties are returned when calling [get-invitations](https://auth0.com/docs/api/management/v2/#!/Organizations/get_invitations) and cannot be requested. The current implementation of `all_organization_invitations` does not enable passing `include_totals`. 
This results in client applications reimplementing paging logic that is already solved by the `start`, `limit`, and `total` properties.
Given that the API already expects `include_totals`, this MR adds the missing parameter to `organizations.all_organization_invitations`.
- Updated `organizations.all_organization_invitations` to include expected parameters for pagination:
- include_totals
- Per [API documentation](https://auth0.com/docs/api/management/v2/#!/Organizations/get_invitations), returning the total is noted as …
> Add `include_totals` pagination parameter to `all_organization_invitations`

- README.rst
- auth0/v3/asyncify.py
- auth0/v3/management/__init__.py
- auth0/v3/management/async_auth0.py
- auth0/v3/management/auth0.py
- auth0/v3/test_async/test_async_auth0.py
Add feature to share a single session across multiple services in Auth0
```py
async with Auth0('domain', 'mgmt_api_token') as auth0:
user = await auth0.users.get_async(user_id)
connection = await auth0.connections.get_async(connection_id)
auth0 = Auth0('domain', 'mgmt_api_token');
session = SingletonAuth0AiohttpClientSession.get_aiohttp_client_session()
auth0.set_session(session)
user = await auth0.users.get_async(user_id)
connection = await auth0.connections.get_async(connection_id)
await session.close()
```
fixes #317 
> Add AsyncAuth0 to share a session among many services

- .pre-commit-config.yaml
This PR fixes the Python3 test suite for the SDK, which has been failing during the `pre-commit run --all-files` step asking for GitLab authentication credentials. This was due to the `.pre-commit-config.yaml` file referencing the GitLab mirror for the project, as opposed to GitHub.
Internal ticket SDK-3883
This change fixes test coverage
> fix: Resolve Python3 tests failing with missing GitLab credentials

- README.md
- auth0/v3/management/__init__.py
- auth0/v3/management/auth0.py
- auth0/v3/management/client_credentials.py
- auth0/v3/test/management/test_auth0.py
- auth0/v3/test/management/test_client_credentials.py
Add get all, get by id, create and delete for client credentials.
> [SDK-3866] Add support for managing client credentials

- auth0/v3/management/branding.py
- auth0/v3/test/management/test_branding.py
The type argument is not required for `update_template_universal_login`
fixes #452
> Remove unnecessary type param from update_template_universal_login

- README.md
Removed legacy example from README. 
A Community user ran into it [here](https://community.auth0.com/t/google-oauth2-login-with-python-package-encountered-weird-error/97913/) and I spoke to @adamjmcgrath on Slack to confirm.
> Removed legacy example from README

- auth0/management/branding.py
- auth0/test/management/test_branding.py
Adding:
https://auth0.com/docs/api/management/v2#!/Branding/get_default_branding_theme
https://auth0.com/docs/api/management/v2#!/Branding/get_branding_theme
https://auth0.com/docs/api/management/v2#!/Branding/delete_branding_theme
https://auth0.com/docs/api/management/v2#!/Branding/patch_branding_theme
https://auth0.com/docs/api/management/v2#!/Branding/post_branding_theme
fixes #475
> Add branding theme endpoints

- EXAMPLES.md
Error Handling and Async applies to both Auth and Mngmnt APIs
> Fix indenting on EXAMPLES.md

- auth0/management/async_auth0.py
- auth0/management/auth0.py
Fix Intellisense for `Auth0` class
fixes #483
> Fix intellisense on Auth0 class

- auth0/authentication/get_token.py
- auth0/test/authentication/test_get_token.py
Change `scope`, `realm` and `audience` arguments to keyword args, since these parameters are optional: http://auth0.com/oauth/grant-type/password-realm
Fixes #482
> Make pw realm params optional

- CHANGELOG.md
- auth0/__init__.py
**Fixed**
- Make pw realm params optional [\#484](https://github.com/auth0/auth0-python/pull/484) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Fix intellisense on Auth0 class [\#486](https://github.com/auth0/auth0-python/pull/486) ([adamjmcgrath](https://github.com/adamjmcgrath))
> Release 4.1.1

- auth0/authentication/token_verifier.py
- auth0/test/authentication/test_token_verifier.py
This PR adds the parameter `cache_ttl` to `AsymmetricSignatureVerifier`. This new, optional parameter allows setting the cache TTL for the underlying `JwksFetcher`. This allows caching the JWK set for more (or less) time than the default 600 seconds.
`AsymmetricSignatureVerifier` had to be moved below `JwksFetcher` because it now references it, so the latter has to be defined earlier in the file.
This closes [#489](https://github.com/auth0/auth0-python/issues/489).
- #489
> Add cache_ttl param to AsymmetricSignatureVerifier

- CHANGELOG.md
- auth0/__init__.py
**Added**
- Add cache_ttl param to AsymmetricSignatureVerifier [\#490](https://github.com/auth0/auth0-python/pull/490) ([matei-radu](https://github.com/matei-radu))
> Release 4.2.0

- EXAMPLES.md
- auth0/authentication/async_token_verifier.py
- auth0/authentication/base.py
- auth0/authentication/client_authentication.py
- auth0/authentication/database.py
- auth0/authentication/delegated.py
- auth0/authentication/enterprise.py
- auth0/authentication/get_token.py
- auth0/authentication/passwordless.py
- auth0/authentication/revoke_token.py
- auth0/authentication/social.py
- auth0/authentication/token_verifier.py
- auth0/authentication/users.py
- auth0/exceptions.py
- auth0/rest.py
- auth0/rest_async.py
- auth0/types.py
- auth0/utils.py
- docs/source/conf.py
- mypy.ini
Fixes partially #470.
The goal is not to add complete type hints to the library, but only were it is beneficial. There are some code patterns that break mypy rules (e.g.  Liskov substitution principle), and I'm not aiming at doing refactors, so once most of the type hints will be added, I'll write a mypy configuration accordingly.
I'm going for the `from __future import annotations` import, to improve type hints readability.
Noticed a couple things:
- This has been introduced two years ago, should it be deprecated now?
https://github.com/auth0/auth0-python/blob/44d6d0ec5c0a098a6d333e7f24d784416da07bca/auth0/rest.py#L108-L111
- Could these methods be transformed into properties/class variables?
https://github.com/auth0/auth0-python/blob/44d6d0ec5c0a098a6d333e7f24d784416da07bca/auth0/rest.py …
> Add type hints to base and `authentication`

- auth0/asyncify.py
- auth0/test_async/test_asyncify.py
Asyncifying authentication classes doesn't work because the asyncify method was assuming the wrong signature.
fixes #498 
```py
AsyncGetToken = asyncify(GetToken)
get_token = AsyncGetToken(domain, client_id)
response = await self.get_token.login_async(
username=username,
password=password,
realm="Username-Password-Authentication",
scope="openid profile email",
)
```
> Fix async auth client

- auth0/management/connections.py
- auth0/test/management/test_connections.py
Add option to pass `name` parameter to `Connections.all` endpoint https://auth0.com/docs/api/management/beta/v2/get-all-connections
fixes #496
> Add connections.all name parameter

- auth0/authentication/get_token.py
- auth0/test/authentication/test_get_token.py
Add option to pass `auth0-forwarded-for` for the password grant. (the only other grant that advertises using this is the [token exchange](https://auth0.com/docs/api/authentication#token-exchange-for-native-social) endpoint, but we don't support that)
fixes #240
> Add forwardedFor option to password grant login

- docs/requirements.txt
- requirements.txt
Fix docs publishing. [Read the docs needs to install sphinx](https://github.com/auth0/auth0-python/blob/master/.readthedocs.yaml#L9) from `docs/requirements.txt`
fixes #503
> Fix docs publishing

- .readthedocs.yaml
- docs/requirements.txt
- requirements.txt
It seems that Sphinx needs the pyjwt dependency when publishing
See #503
> Fix docs pt 2

- auth0/asyncify.py
- auth0/authentication/users.py
- auth0/test_async/test_asyncify.py
This PR fixes a bug that is currently in the Auth0 SDK `asyncify` wrapper where it falls through to the AsyncManagementClient when the class being wrapped doesn't inherit from the `AuthenticationBase` class. This doesn't work for the `Users` client, as that shouldn't require a management token.
Currently, using the `Users` client with the async wrapper fails with the following error:
```python
TypeError: asyncify.<locals>.AsyncManagementClient.__init__() missing 1 required positional argument: 'token'
```
The approach I took was to implement a new `BareAsyncClient` for this case, however I'm not 100% wedded to this approach so feel free to tell me to have another go!
I've added a test for this functionality to check that we don't need to add the token when calling the Users client when …
> Fix asyncify for users client where token is not required

- auth0/authentication/async_token_verifier.py
- auth0/authentication/token_verifier.py
- auth0/test/authentication/test_token_verifier.py
Validate the `org_name` claim when `organization` config isn't an org id (doesn't include the `org_` prefix)
> [SDK-4394] Add organization name validation

- auth0/management/client_grants.py
- auth0/management/device_credentials.py
- auth0/management/grants.py
- auth0/management/hooks.py
- auth0/management/logs.py
- auth0/management/organizations.py
- auth0/management/resource_servers.py
- auth0/management/roles.py
- auth0/management/rules.py
- auth0/management/users.py
Paginated endpoints, like `organizations.all_organization_members` return a `list` when `include_totals` is `None` or `False` and a `dict` when `include_totals` is `True`. Currently the return type of these is `list[dict[str, Any]]` and so static type checkers will fail when the developer sets `include_totals=True`.
I've removed the return type for these because:
- The existing return type `list[dict[str, Any]]` is not particularly useful
- Using a Union type will be a breaking change for those using the endpoint without pagination
- Trying to fix this in a non breaking way would require overloads and the `typing-extensions` package (as 3.7 doesn't support `typing.Literal`), which to change the type to return `dict[str, Any]` as well as `list[dict[str, Any]]` is not justified.
Type …
> Remove return types for paginated endpoints

- mypy.ini
Statically checking attr's is failing for `AsyncAuth0` because the attributes are added dynamically.
I've disabled that type-checking rule because - type support for this SDK is only very basic at the moment. But we will improve it in the future if/when we can get structured API data (like OpenAPI 3) from the Auth0 Management API.
fixes #514
> Fix for async types

- mypy.ini
This package started publishing types in 4.4, but the way we add async classes and methods makes type checking unfeasible.
Revert publishing types externally until a better solution is available (this will probably be by generating the SDK).
fixes #514 
See https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
> Revert publishing types

- pyproject.toml
Fix issue with Python dependency version in 4.4.1
fixes #517 
1. Start a new python project with:
```
[tool.poetry.dependencies]
python = ">=3.10"
```
In your pyproject.toml file
3. Add `auth0-python` with poetry `poetry add ../path/to/auth0-python`
> Fix python dependency version

- auth0/management/organizations.py
- auth0/test/management/test_organizations.py
Add `fields` and `include_fields` option to `all_organization_members`
fixes #534 
https://auth0.com/docs/api/management/v2/organizations/get-members
> [SDK-4656] Add fields to all_organization_members

- auth0/authentication/database.py
- auth0/test/authentication/test_database.py
Authentication API, the Database class, added the `organization` param to the `change_password` method.
https://auth0.com/docs/api/authentication#change-password
> Authentication API, the Database classs, Add the organization param to the change_password method

- pyproject.toml
This PR:
- Bumps the `cryptography` dependency version to `^41.0.5` (up from `^41.0.3`) to address [CVE-2023-45803](https://www.cve.org/CVERecord?id=CVE-2023-45803).
- Pins the weak dependency for `urllib3` (by way of `requests`) to `^2.0.7` to address [CVE-2023-5363](https://www.cve.org/CVERecord?id=CVE-2023-5363).
N/A
N/A
> chore(dependencies): Update `cryptography` and pin `urllib3`

- auth0/authentication/get_token.py
- auth0/management/client_grants.py
- auth0/management/organizations.py
- auth0/test/authentication/test_get_token.py
- auth0/test/management/test_client_grants.py
- auth0/test/management/test_organizations.py
- Add optional organization parameter to client credentials grant
- Add Management API endpoints to /client-grants and /organizations
> [SDK-4544] Add orgs in client credentials support

- CHANGELOG.md
**Added**
- [SDK-4544] Add orgs in client credentials support [\#549](https://github.com/auth0/auth0-python/pull/549) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Authentication API, the Database classs, Add the organization param to the change_password method [\#539](https://github.com/auth0/auth0-python/pull/539) ([shchotse](https://github.com/shchotse))
- Retry all methods on 429 [\#518](https://github.com/auth0/auth0-python/pull/518) ([adamjmcgrath](https://github.com/adamjmcgrath))
[SDK-4544]: https://auth0team.atlassian.net/browse/SDK-4544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 4.6.0

- auth0/management/users.py
Fix type hint for `link_user_account` to match the actual response from the API
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- Any alternative designs or approaches considered
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or …
> fix type hint for link_user_account

- .github/workflows/test.yml
- auth0/rest_async.py
- auth0/test_async/test_async_auth0.py
- auth0/test_async/test_async_token_verifier.py
- auth0/test_async/test_asyncify.py
Broke rest_sync in #518 and an issue in the async tests meant it didn't get picked up.
fixes #555
> Fix rest_async and async tests

- .github/workflows/publish.yml
- .github/workflows/test.yml
The latest version of poetry-dynamic-versioning is causing issue with the build
(The tests will fail because the build config yaml is coming from `master`)
> Fix build issue with latest poetry-dynamic-versioning

- .github/workflows/docs.yml
Despite being advertised as needing to be upgraded in lockstep, the new versions just [don't actually function](https://github.com/auth0/auth0-python/actions/runs/7275691495/job/19824034193) so lets revert for now
> Revert docs actions upgrade

- .github/workflows/publish.yml
Comparing with [other repos ](https://github.com/auth0/auth0-spa-js/blob/4314cf05d6fbe59bfbef6e73453ca4c65a1f92b5/.github/workflows/release.yml#L10)it seems like the permissions and github_token secret were referenced differently, I think that should fix the issue seen when attempting to publish 🤞🏻 
> ci(publish): make contents write and fix secrets reference

- .github/workflows/publish.yml
Poetry build seems to create versioned content, so we need the tag made before even that step
> ci(publish): move release creation before any poetry steps

- .github/workflows/publish.yml
Given that we create the release/tag via the API, the local git repo doesn't get updated so the poetry dynamic versioning still can't find the tag.
To make things simpler for now, I propose we make this repo a manual release trigger and change the new release flow to:
* Release PR made
* Release PR merged
* Tag created and merged
* Release workflow triggered
> ci(publish): only run on manual workflow, remove tag check

- .github/workflows/snyk.yml
- Upgrade python version from 3.7 to 3.8 in sync github action, as sync is about to deprecate that github action
- https://updates.snyk.io/final-reminder-on-snyk-cli-images-and-snyk-images-containing-eol-software-297657
- https://docs.snyk.io/scm-ide-and-ci-cd-integrations/snyk-ci-cd-integrations/eol-policy-snyk-images/images-no-longer-supported-by-snyk
> Upgrade python 3.7 to 3.8 in sync github action

- .github/actions/rl-scanner/action.yml
- .github/workflows/publish.yml
- .github/workflows/rl-scanner.yml
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
- Any alternative designs or approaches considered
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should …
> Add RL-Secure workflow for scanning build artifacts

- auth0/authentication/back_channel_login.py
- auth0/authentication/get_token.py
- auth0/test/authentication/test_back_channel_login.py
- auth0/test/authentication/test_get_token.py
- Added support for Client Initiated Backchannel Authorization.
- [/bc-authorize](https://auth0.com/docs/api/authentication?http#back-channel-login) is added.
- Extended the [/oauth/token](https://auth0.com/docs/api/authentication?http#-post-oauth-token-) to support CIBA.
- [User Authentication with CIBA](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-initiated-backchannel-authentication-flow/user-authentication-with-ciba)
- [Configure Client-Initiated Backchannel Authentication](https://auth0.com/docs/get-started/applications/configure-client-initiated-backchannel-authentication#integrate-guardian-sdk-into-your-application)
> Adding Support For Back Channel Login

- .github/workflows/publish.yml
- .github/workflows/rl-scanner.yml
> fix: RL Scanner

- auth0/authentication/get_token.py
- auth0/management/users.py
- auth0/test/authentication/test_get_token.py
- auth0/test/management/test_users.py
- Added support for Federated Login for Authentication and Management APIs.
- Extended the [/oauth/token (https://oktawiki.atlassian.net/wiki/spaces/AFG1/pages/3206646683/DRAFT+APIs+Quick+Reference) to support federated login.
- Two new endpoints added to [Users.py](https://github.com/auth0/auth0-python/blob/master/auth0/management/users.py) i.e.
- Get a List of All Token Sets
- Revoking a token set
- [Internal Reference](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-initiated-backchannel-authentication-flow/user-authentication-with-ciba)
> feat:Adding Support For Federated Login

- auth0/authentication/pushed_authorization_requests.py
- auth0/rest.py
- Fix for  `401: Unauthorized `for PAR Requests
> Fix: Unauthorized Access Error For PAR

- auth0/authentication/get_token.py
- auth0/test/authentication/test_get_token.py
- Modified the  function name from `federated_access_token` to `access_token_for_connection`.
> fix:Change the federated connection function name

- .github/workflows/snyk.yml
> fix: update snyk scan to utilize newest methodology

- auth0/authentication/get_token.py
- auth0/management/users.py
- auth0/test/authentication/test_get_token.py
- auth0/test/management/test_users.py
- Added support for Federated Login for Authentication and Management APIs.
- Extended the [/oauth/token (https://oktawiki.atlassian.net/wiki/spaces/AFG1/pages/3178596704/RFC+Federated+Connections+Access+Tokens+-+EA) to support federated login.
- Two new endpoints added to [Users.py](https://github.com/auth0/auth0-python/blob/master/auth0/management/users.py) i.e.
- Get a List of All Token Sets
- Revoking a token set
- [Internal Reference](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-initiated-backchannel-authentication-flow/user-authentication-with-ciba)
> feat: Federated Connections Support
