examples/flask-webapp/README.md

This addresses part of issue #129 in [Auth0 docs](https://github.com/auth0/docs) repo.

Improved readme and fixed some typos.

---

examples/flask-webapp/public/app.js
examples/flask-webapp/templates/home.html

Changed deprecated auth0 widget to auth0 lock library

Auth0 lock

---

examples/flask-api/server.py

Added a error handler/wrapper since some paths in the seed project
returned raw python objects.

Return a valid response from all error handling paths.

---

README.rst

This pull request corrects the capitalization of JSON 🤓
https://auth0.com/docs/jwt

Correct capitalization of JSON in README

---

README.rst

Tiny thing but might let people stumble.

Removed hardcoded Domain Name in Example

---

auth0/v3/authentication/enterprise.py
auth0/v3/authentication/get_token.py
auth0/v3/authentication/logout.py
auth0/v3/authentication/passwordless.py
auth0/v3/authentication/social.py
auth0/v3/management/blacklists.py
auth0/v3/management/client_grants.py
auth0/v3/management/clients.py

Doubts -> 
`non interactive client` (for token issuing) and `client credentials grant`

rename clients to applications

---

README.rst

Fixed several typos in the main readme doc.

Fix typos in readme

---

DEVELOPMENT.rst

Use appropriate indents in list, add the reference to the changelog and format filenames and variable as inline code.

fixed and enhanced formatting of development guide

---

README.rst

closes #149 
was a markdown link instead of an rst link

fix link in readme

---

.snyk

Ignore unaffected vulnerabilities for requests library.

Add snyk policy file to ignore unaffected vulnerable packages

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Please push changes directly to the `add-issue-templates` branch and approve + merge when ready!

Adding GitHub issue and PR templates

---

auth0/v3/authentication/base.py
auth0/v3/management/rest.py
auth0/v3/test/authentication/test_base.py
auth0/v3/test/management/test_rest.py

- Update telemetry format to comply with internal RFC.
- Remove `requests` version from telemetry.
`SDK-702`

Update telemetry format

---

auth0/v3/management/auth0.py
auth0/v3/management/rest.py
auth0/v3/management/roles.py
auth0/v3/management/users.py
auth0/v3/test/management/test_auth0.py
auth0/v3/test/management/test_rest.py
auth0/v3/test/management/test_roles.py
auth0/v3/test/management/test_users.py

Adds all missing endpoints for **Roles** and User/Role **Permissions**.

Add Roles and Permissions endpoints

---

requirements.txt

Move back the minimum required version a bit to the one we require. In the end, the package manager will resolve the best latests version that can satisfy all the app dependencies.
Closes https://github.com/auth0/auth0-python/issues/201

Update minimum "requests" version to 2.14.0

---

CHANGELOG.md

Updated the changelog
Closes https://github.com/auth0/auth0-python/issues/200

Re-categorize changelog entry

---

README.rst

Adds a note about bot protection. 
There's no note about the login hint / screen hint as this SDK doesn't allow specifying additional authentication parameters
https://auth0.com/docs/anomaly-detection/bot-protection

Add note in the readme about bot protection

---

README.rst

Reverts auth0/auth0-python#238

Revert "Add note in the readme about bot protection"

---

.circleci/config.yml
requirements.txt
setup.py

This PR drops support for the `requirements.txt` file and makes use of `install_requires` and `extras_require`. Doing this fixes the installation of this package using `pip`.
```
╰─$ python3 -m venv /tmp/venv
╰─$ /tmp/venv/bin/pip3 install /Users/lbalmaceda/Python/auth0-python
Processing /Users/lbalmaceda/Python/auth0-python
Collecting requests>=2.14.0
Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyjwt[crypto]>=1.7.1
Using cached PyJWT-2.0.1-py3-none-any.whl (15 kB)
Collecting chardet<5,>=3.0.2
Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
Using cached …
```

Remove requirements.txt file

---

.circleci/config.yml

This PR adds the configuration necessary to support automatic publishing through our internal Ship tool.

[SDK-3412] Add ship/orb configuration to CI

---

auth0/v3/management/auth0.py
auth0/v3/test/management/test_auth0.py

Pass rest_options through Auth0 constructor

---

.circleci/config.yml

https://circleci.com/developer/orbs/orb/auth0/ship

Update ship/orb version to final

---

CHANGELOG.md
V4_MIGRATION_GUIDE.md
auth0/__init__.py

**Added**
- Add support for private_key_jwt [\#456](https://github.com/auth0/auth0-python/pull/456) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Add support for managing client credentials [\#459](https://github.com/auth0/auth0-python/pull/459) ([adamjmcgrath](https://github.com/adamjmcgrath))
**Security**
- Update pyjwt [\#460](https://github.com/auth0/auth0-python/pull/460) ([adamjmcgrath](https://github.com/adamjmcgrath))
**Changed**
- Publish Python Support Schedule [\#454](https://github.com/auth0/auth0-python/pull/454) ([evansims](https://github.com/evansims))
**⚠️ BREAKING CHANGES**
- Remove deprecated methods [\#461](https://github.com/auth0/auth0-python/pull/461) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Remove v3 folder …

Release 4.0.0

---

CHANGELOG.md
auth0/__init__.py

**Added**
- Add branding theme endpoints [\#477](https://github.com/auth0/auth0-python/pull/477) ([adamjmcgrath](https://github.com/adamjmcgrath))
- [SDK-4011]  Add API2 Factor Management Endpoints [\#476](https://github.com/auth0/auth0-python/pull/476) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Use declarative setup with `pyproject.toml` [\#474](https://github.com/auth0/auth0-python/pull/474) ([Viicos](https://github.com/Viicos))
[SDK-4011]: https://auth0team.atlassian.net/browse/SDK-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 4.1.0

---

auth0/management/branding.py
auth0/test/management/test_branding.py

Fixes https://github.com/auth0/auth0-python/issues/494

Fix update_template_universal_login

---

CHANGELOG.md
auth0/__init__.py

**Added**
- [SDK-4394] Add organization name validation [\#507](https://github.com/auth0/auth0-python/pull/507) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Add type hints to `management` [\#497](https://github.com/auth0/auth0-python/pull/497) ([Viicos](https://github.com/Viicos))
**Fixed**
- Fix asyncify for users client where token is not required [\#506](https://github.com/auth0/auth0-python/pull/506) ([cgearing](https://github.com/cgearing))
[SDK-4394]: https://auth0team.atlassian.net/browse/SDK-4394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 4.4.0

---

CHANGELOG.md

**Fixed**
- Fix for async types [\#515](https://github.com/auth0/auth0-python/pull/515) ([adamjmcgrath](https://github.com/adamjmcgrath))

Release 4.4.1

---

CHANGELOG.md

**Fixed**
- Fix python dependency version [\#522](https://github.com/auth0/auth0-python/pull/522) ([adamjmcgrath](https://github.com/adamjmcgrath))
- Revert publishing types [\#521](https://github.com/auth0/auth0-python/pull/521) ([adamjmcgrath](https://github.com/adamjmcgrath))

Release 4.4.2

---

CHANGELOG.md

**Fixed**
- Fix rest_async and async tests [\#556](https://github.com/auth0/auth0-python/pull/556) ([adamjmcgrath](https://github.com/adamjmcgrath))
- fix type hint for link_user_account [\#552](https://github.com/auth0/auth0-python/pull/552) ([tzzh](https://github.com/tzzh))

Release 4.6.1

---

.github/workflows/rl-scanner.yml
.github/workflows/test.yml
README.md

Fixing the Github Workflow Issues

---

.github/actions/rl-scanner/action.yml
.github/workflows/rl-scanner.yml

Adding Version To RL Scanner
